version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producao_app
    restart: always
    ports:
      - 8084:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://producao_dbhost:5432/producao_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:15
    restart: always
    container_name: producao_dbhost
    environment:
      - POSTGRES_DB=producao_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5436:5432